import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import {
  Button,
  Heading,
  Image,
  SimpleGrid,
  Stack,
  Text,
} from '@chakra-ui/react'
import { Carousel } from 'react-bootstrap'

const Home = ({ characters }) => {
  return (
    <Stack className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap"
          rel="stylesheet"
        />
        <link
          rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.min.css"
        />
      </Head>

      <hr />
      <Carousel fade>
        <Carousel.Item interval={1000}>
          <Image
            className="d-block w-100"
            src="/cold-pressed-coconut-oil-80.jpg"
            alt="First slide"
            height="450px"
          />
          {/* <Carousel.Caption>
            <Heading as="h1" size="4xl" noOfLines={1}>
              cold pressed coconut oil
            </Heading>
            <a href="#services">
            <Button className="book-btn">Book Now</Button>
            </a>
          </Carousel.Caption> */}
        </Carousel.Item>
        <Carousel.Item interval={1000}>
          <Image
            className="d-block w-100"
            src="/cold-pressed-groundnut-oil-70.jpg"
            alt="Second slide"
            height="450px"
          />
          {/* <Carousel.Caption>
            <Heading as="h1" size="4xl" noOfLines={1}>
              cold pressed groundnut oil
            </Heading>
            <a href="#services">
            <Button className="book-btn">Book Now</Button>
            </a>
          </Carousel.Caption> */}
        </Carousel.Item>
        <Carousel.Item interval={1000}>
          <Image
            className="d-block w-100"
            src="/cold-pressed-mustard-oil-70.jpg"
            alt="Third slide"
            height="450px"
          />
          {/* <Carousel.Caption>
            <Heading as="h1" size="4xl" noOfLines={1}>
              cold pressed mustard oil
            </Heading>
            <a href="#services">
            <Button className="book-btn">Book Now</Button>
            </a>
          </Carousel.Caption> 
          */}
        </Carousel.Item>
      </Carousel>
      <Stack textAlign="center">
        <Text fontSize="5xl" fontWeight="bold" mt="20px">
          From Farm to Fork
        </Text>
      </Stack>
      <SimpleGrid columns={[2, 2, 4, 4]} spacing={5} p="10px">
        <Stack p="5px" alignItems="center">
          <Image
            src="/handpicked-ingredients.jpg"
            alt="handpicked-ingredients"
            width="100px"
            height="100px"
          />
          <Text fontSize="s" fontWeight="bold" textAlign="center">
            Ingredients chosen with care
          </Text>
          <Text fontSize="s" p="10px" textAlign="center">
            Ingredients sourced locally and free of genetically engineered
            organisms
          </Text>
        </Stack>
        <Stack p="5px" alignItems="center">
          <Image
            src="/carbon-footprint.jpg"
            alt="carbon-footprint"
            width="100px"
            height="100px"
          />
          <Text fontSize="s" fontWeight="bold" textAlign="center">
            Lowest Carbon Footprint
          </Text>
          <Text fontSize="s" p="10px" textAlign="center">
            Conventional environmentally friendly agriculture and
            agro-processing methods to reduce emissions & pollutants.
          </Text>
        </Stack>
        <Stack p="5px" alignItems="center">
          <Image
            src="/empowerment.jpg"
            alt="empowerment"
            width="100px"
            height="100px"
          />
          <Text fontSize="s" fontWeight="bold" textAlign="center">
            Farmer Empowerment
          </Text>
          <Text fontSize="s" p="10px" textAlign="center">
            Support the livelihood and well-being of local farmers, as well as
            training and employment opportunities for rural Indians,
            particularly women.
          </Text>
        </Stack>
        <Stack p="5px" alignItems="center">
          <Image
            src="/package.jpg"
            alt="package"
            width="100px"
            height="100px"
          />
          <Text fontSize="s" fontWeight="bold" textAlign="center">
            Lovingly Packed and Delivered
          </Text>
          <Text fontSize="s" p="10px" textAlign="center">
            Genuine food goods that are hygienically packed, hand-labelled, and
            carefully delivered to ensure the finest consumer experience.
          </Text>
        </Stack>
      </SimpleGrid>
    </Stack>
  )
}

export const getStaticProps = async (context) => {
  // const res = await fetch('https://rickandmortyapi.com/api/character')
  // const { results }: GetCharacterResults = await res.json()
  return {
    props: {
      characters: [],
    },
  }
}

export default Home
